id                  = "heart-partridge"
english_title       = ""
persian_title       = ""
date_written        = "1/4/1991 کلاردشت ۱۳۷۰/۱/۴"
date_translated     = ""
page_number         = "128"
persian_page_number = "۱۲۸"
source              = ""
tags                = []
notes               = ""
draft               = false
