id                  = "soul-mold"
english_title       = ""
persian_title       = ""
date_written        = "1989 - ۱۳۶۸"
date_translated     = ""
page_number         = "66"
persian_page_number = "۶۶"
source              = ""
tags                = []
notes               = ""
draft               = false
