id                  = "water-cage"
english_title       = ""
persian_title       = ""
date_written        = "July 25 1993 - ۱۳۷۲/۵/۳"
date_translated     = ""
page_number         = "149"
persian_page_number = "۱۴۹"
source              = ""
tags                = []
notes               = ""
draft               = false
