id                  = "bird-behind-wall"
english_title       = "Adobe"
persian_title       = "بوی کاهگل"
date_written        = "Autumn 1989"
date_translated     = "4-8-2026"
page_number         = "12"
persian_page_number = ""
source              = ""
tags                = []
notes               = ""
draft               = false
