id                  = "gone-coming"
english_title       = ""
persian_title       = ""
date_written        = "12/17/1989 ۱۳۶۸/۱۲/۱۷"
date_translated     = ""
page_number         = "100"
persian_page_number = "۱۰۰"
source              = ""
tags                = []
notes               = ""
draft               = false
