id                  = "jungle-bomb"
english_title       = ""
persian_title       = ""
date_written        = "May 9, 1988, Isfahan - ۱۳۶۷/۲/۱۹"
date_translated     = ""
page_number         = "61"
persian_page_number = "۶۱"
source              = ""
tags                = []
notes               = ""
draft               = false
