id                  = "laugh-cry"
english_title       = ""
persian_title       = ""
date_written        = "Nov 1988 - ۱۳۶۷/۹"
date_translated     = ""
page_number         = "62"
persian_page_number = "۶۲"
source              = ""
tags                = []
notes               = ""
