id                  = "life-tune"
english_title       = "Life..."
persian_title       = "زندگی..."
date_written        = "University Quarter, Tehran, 1963 - ۱۳۴۲"
date_translated     = ""
page_number         = "40"
persian_page_number = "۴۰"
source              = ""
tags                = []
notes               = ""
