id                  = "meager-dew"
english_title       = ""
persian_title       = ""
date_written        = "April 15 1992 ۱۳۷۰/۱/۱۶"
date_translated     = ""
page_number         = "131"
persian_page_number = "۱۳۱"
source              = ""
tags                = []
notes               = ""
