id                  = "moonlight-sunlight"
english_title       = "Moonlight, Sunlight"
persian_title       = "مهتاب"
date_written        = "Borojerd 1960 - ۱۳۳۹"
date_translated     = "4-3-2026"
page_number         = "30"
persian_page_number = "۳۰"
source              = ""
tags                = []
notes               = ""
