id                  = "old-news"
english_title       = "Old News"
persian_title       = "آخرین خبر"
date_written        = "1960 - ۱۳۳۹"
date_translated     = ""
page_number         = "28"
persian_page_number = "۲۸"
source              = ""
tags                = []
notes               = ""
