id                  = "shadow-daughter"
english_title       = "To my daughter Shade"
persian_title       = "به دخترم سایه"
date_written        = "1980s دهه ۱۳۶۰"
date_translated     = "4-29-26"
page_number         = "48"
persian_page_number = "۴۸"
source              = ""
tags                = []
notes               = ""
