id                  = "stay-go"
english_title       = "Stay"
persian_title       = "می خواهی بمان"
date_written        = ""
date_translated     = ""
page_number         = ""
persian_page_number = ""
source              = ""
tags                = []
notes               = ""
